---

- name: Gather AWS instances facts
  hosts: master, slave
  user: ubuntu
  tasks:
    - action: ec2_metadata_facts
  tags: [always]


- name: Deploying SM engine code to the slaves
  hosts: slave
  user: ubuntu
  gather_facts: false

  roles:
    - role: sm_engine
  tags: [slave]


- name: Deploying SM engine code to the master
  hosts: master
  user: ubuntu
  gather_facts: true

  vars:
    spark_master_host: "spark://{{ ansible_hostname }}.{{ aws_region }}.compute.internal:7077"
    sm_web_app_url: "{{ web_public_url }}"
    es_host: "{{ sm_es_host }}"
    es_port: "{{ sm_es_port }}"
    es_user: "{{ sm_es_user }}"
    es_password: "{{ sm_es_password }}"

  roles:
    - role: supervisorctl
    - role: sm_annotate_daemon

  tags: [master]
