---

- name: Spinning up AWS instances
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    components: ''

  tasks:
    - debug: var=components
    - debug: var=aws_key_name

    - name: Spin up SM instances
      shell: >
        {{ sm_cluster_autostart_python }} aws_instance_manager.py create --key-name {{ aws_key_name }}
        --components {{ components }} --stage {{ stage }}
        {{ ' --credentials-file' if cred_file is defined else '' }}

    - meta: refresh_inventory

  tags: ["web", "spark", "elk"]


- name: Wait for SSH on Spark instances to come up
  hosts: localhost
  user: ubuntu
  gather_facts: True

  tasks:
    - name: Wait for SSH on master to come up
      wait_for:
        host: "{{ hostvars['master-1']['ansible_ssh_host'] }}"
        port: 22
        timeout: 300
        state: started

    - name: Wait for SSH on slaves to come up
      wait_for:
        host: "{{ hostvars[item]['ansible_ssh_host'] }}"
        port: 22
        timeout: 300
        state: started
      with_items: "{{ groups['slave'] }}"

  tags: ["spark"]