---

- name: Check if supervisord daemon is running
  shell: supervisorctl status
  args:
    executable: /bin/bash
  register: supervisorctl_status_out
  failed_when: false

- name: Start supervisord daemon
  shell: >
    supervisord -c /etc/supervisor/supervisord.conf -l /var/log/supervisor/supervisord.log
    && supervisorctl stop all
  args:
    executable: /bin/bash
  register: command_result
  when: "'no such file' in supervisorctl_status_out.stdout"
