---

#- name: Set kernel inotify watch limit to 524288
#  sysctl:
#    name: fs.inotify.max_user_watches
#    value: 524288
#    state: present

- name: Install software-properties-common
  become: yes
  apt: name=software-properties-common state=present

- name: Install nvm
  shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
  args:
    creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"

- name: Ensure nvm installs yarn for every version
  lineinfile:
    path: "{{ ansible_env.HOME }}/.nvm/default-packages"
    create: yes
    line: yarn

# This controls the default version only.
# Individual projects can install other versions to match their own requirements.
# NOTE: To actually use NVM in Ansible, you need to set the executable as /bin/bash and prefix the command
# with "{{ sm_activate_nvm }} &&". Ansible doesn't support anything tidier: https://github.com/ansible/ansible/issues/4854
- name: Install Node.js
  shell: . ~/.nvm/nvm.sh && nvm install {{ nodejs_version }} && nvm alias default {{ nodejs_version }}
  args:
    executable: /bin/bash
