---

- name: Install Ansible
  become: yes
  pip:
    name: ansible
    version: "{{ sm_cluster_autostart_ansible_version }}"
    state: present
    executable: "{{ miniconda_prefix }}/envs/{{ miniconda_env['name'] }}/bin/pip"

- name: Make sure {{ sm_ansible_home }} exists
  become: yes
  file: path={{ sm_ansible_home }} owner=ubuntu group=ubuntu state=directory mode=0755

- name: Copy private key for SSHing to the master
  copy: src={{ spark_key_file }} dest="/home/ubuntu/.ssh/id_rsa" owner=ubuntu group=ubuntu mode="u=rw,g=,o="

- name: Make sure .aws directory exists
  file: path=/home/ubuntu/.aws/
        state=directory mode=0755
        owner=ubuntu group=ubuntu
  when: aws_access_key_id is defined

- name: Put aws credentials file into the home dir
  template: src=aws_credentials.j2
            dest=/home/ubuntu/.aws/credentials mode=0600
            owner=ubuntu group=ubuntu
  when: aws_access_key_id is defined
