---

elasticsearch_version: "{{ elk_version }}"
elasticsearch_bound_to_any_host: true
kibana_version: "{{ elk_version }}"
kibana_es_port: "{{ elk_es_port }}"

nginx_raw_config: |
  server {
      listen 80 default_server;
      listen [::]:80 default_server;
      server_name _;
      return 301 https://$host$request_uri;
  }

  server {
      # SSL configuration
      listen 443 ssl http2 default_server;
      listen [::]:443 ssl http2 default_server;
      ssl_certificate ssl/{{ ssl.cert }};
      ssl_certificate_key ssl/{{ ssl.key }};

      auth_basic "Restricted Access";
      auth_basic_user_file /etc/nginx/passwdfile;

      location / {
          proxy_pass http://localhost:5601;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection 'upgrade';
          proxy_set_header Host $host;
          proxy_cache_bypass $http_upgrade;
      }
  }
