---

- name: Make sure a folder for the config file exists
  file: path={{ sm_ansible_home }}/aws/{{ stage }}/group_vars/all state=directory mode=0755

- name: Upload {{ stage }}/group_vars/all/vars.yml with variables resolved
  template:
    src: "../{{ stage }}/group_vars/all/vars.yml"
    dest: "{{ sm_ansible_home }}/aws/{{ stage }}/group_vars/all/vars.yml"
    owner: ubuntu
    group: ubuntu
    mode: "0600"

- name: Update the inventory file
  command: "{{ sm_cluster_autostart_python }} update_inventory.py --stage={{ stage }}"
  args:
    chdir: "{{ sm_ansible_home }}/aws"

- name: Make sure {{ sm_ansible_home }}/aws/logs exists
  become: yes
  file: path={{ sm_ansible_home }}/aws/logs owner=ubuntu group=ubuntu state=directory mode=0755

- name: Supervisord config for the cluster_auto_start_daemon
  template: src=sm-cluster-autostart-daemon.supervisor.j2
            dest=/etc/supervisor/sm-cluster-autostart-daemon.supervisor
            owner=ubuntu group=ubuntu mode=0600

- name: Update and restart supervisor app
  supervisorctl:
    name: "{{ sm_cluster_autostart_app_name }}"
    state: restarted
