---

- name: Copy sm-lithops-daemon supervisor config file
  template: src=sm-lithops-daemon.supervisor.j2 dest=/etc/supervisor/{{ sm_lithops_daemon_app_name }}.supervisor
            mode=0600 owner=ubuntu group=ubuntu

- name: Update and restart supervisor app
  supervisorctl:
    name: "{{ sm_lithops_daemon_app_name }}:"
    state: restarted
