---

- name: ELK instance configuration
  hosts: elk
  user: ubuntu
  gather_facts: no

  tasks:
    - name: Install python3-simplejson
      become: yes
      raw: apt-get update && apt-get install -y python3-simplejson


- name: Install and configure ES, Kibana, Nginx
  hosts: elk
  user: ubuntu
  gather_facts: yes

  roles:
    - role: base
      tags: [base]

    - role: elk
      tags: [elk]
