---

- name: Gather Ansible facts about elk and web hosts
  hosts: [elk, web, master, slave]
  user: ubuntu
  gather_facts: yes
  tasks:
    - name: Gather AWS instance facts
      action: ec2_metadata_facts
  tags: [always]


- name: SM master, slave instances basic configuration
  hosts: [master, slave]
  user: ubuntu
  gather_facts: no
  roles:
    - role: base
      become: yes
      swapsize: 16384
  tags: [base, slave]


- name: SM spark slave instances configuration
  hosts: slave
  user: ubuntu
  gather_facts: yes

  roles:
    - role: base
      become: yes
      swapsize: 16384

    - role: spark
      become: yes
      spark_env_extras: "{{ spark_env_extras_slave }}"
      tags: [spark]

    - role: miniconda
      tags: [miniconda]

    - role: sm_spark_slave
      venv: "{{ miniconda_prefix }}"
      conda_env: "{{ miniconda_env.name }}"
      spark_usr_dir: "{{ spark_home }}"
      tags: [sm-spark-slave]
  tags: [slave]


- name: SM spark master instance configuration
  hosts: master
  user: ubuntu
  gather_facts: yes

  vars:
    spark_master_host: "spark://{{ ansible_hostname }}:7077"
    spark_slave_ips: []

  pre_tasks:
    - name: Gather EC2 instance facts
      ec2_metadata_facts:
      tags: [always]

    - name: Create a list of private ip addresses for the slave instances
      set_fact: spark_slave_ips="{{ spark_slave_ips  + [ hostvars[item].ansible_ec2_local_ipv4 ] }}"
      with_items: "{{ groups['slave'] }}"

    - debug: var=spark_slave_ips

  roles:
    - role: base
      become: yes
      swapsize: 16384

    - role: spark
      become: yes
      spark_env_extras: "{{ spark_env_extras_master }}"
      tags: [spark]

    - role: spark_master
      become: yes

    - role: miniconda
      tags: [miniconda]

    - role: supervisor

    - role: filebeat
      tags: [filebeat]

    - role: metaspace_repo
      tags: [metaspace_repo]

    - role: sm_spark_master
      venv: "{{ miniconda_prefix }}"
      conda_env: "{{ miniconda_env.name }}"
      spark_usr_dir: "{{ spark_home }}"
      sm_web_app_url: "{{ web_public_url }}"
      tags: [sm-spark-master]
  tags: [master]
